# Reddit API credentials
# setup guide at https://praw.readthedocs.io/en/latest/getting_started/authentication.html#script-application
reddit: 
    client_id:
    client_secret:
    password:
    user_agent:
    username:

# Choosing clips
subreddit: GlobalOffensive
flair: 'Stream Highlight'    # use '' (single quotes) for flairs with 2+ words
time_filter: day             # one of: hour, day, week, month, year, all
clips: 5                     # number of clips to download
order: random                # ordering of clips on the final video, one of: default, random, reverse

# Script functions
download: True               # whether or not to download the clips
concatenate: True            # whether or not to concatenate the clips into a long video
delete: True                 # delete clips after script is done

# Video 
workdir: ./clips             # folder to keep the downloaded clips
resolution: [1080, 1920]     # resolution target for the clips; CAUTION: format is [y, x]
fps: 60                      # framerate target for the final video
filename: output.mp4         # filename for the final video
